name: Update Backstage Techdocs
description: Updates Backstage Techdocs on Elisa premises
inputs:
  entity:
    description: Backstage entity for documents, e.g. "default/Component/myEntity"
    required: true
  source-dir:
     description: Source directory containing mkdocs.yml and docs subdirectory, e.g. "."
     required: false
     default: .
  output-dir:
     description: Output directory containing generated TechDocs site, e.g. "./site/"
     required: false
     default: ./site/
  s3-access-key-id:
    description: S3 access key id
    required: true
  s3-secret-access-key:
    description: S3 secret access key
    required: true
  s3-bucket:
    description: S3 bucket
    required: true
  s3-region:
    description: S3 region
    required: false
    default: eu-central-1
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Generate documents
      run: |
        npx @techdocs/cli generate \
            --source-dir "${{ inputs.source-dir }}" \
            --output-dir "${{ inputs.output-dir }}"
      shell: bash
    - name: Publish documents
      env:
        AWS_REGION: ${{ inputs.s3-region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.s3-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-access-key }}
      run: |
         npx @techdocs/cli publish \
           --entity "${{ inputs.entity }}" \
           --directory "${{ inputs.output-dir }}" \
           --storage-name "${{ inputs.s3-bucket }}" \
           --publisher-type awsS3
      shell: bash
branding:
  color: blue
  icon: filter
